import { Gabarito } from "next/font/google";
import { BlurFade } from "@/components/ui/blur-fade";


const gabarito = Gabarito({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export default function Showcase() {
  return (
    <div>
      <div className={`${gabarito.className} text-white text-4xl font-bold flex flex-col items-center justify-center font-boldz`}>
        <h1>Some more images generated by Asimov AI</h1>
      </div>
      
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-8 max-w-10xl mx-auto px-4">
   
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 1"
          className="w-full h-full object-cover"
        />
      </div>
    
     
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 2"
          className="w-full h-full object-cover"
        />
      </div>
     
      
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 3"
          className="w-full h-full object-cover"
        />
      </div>
    
      <BlurFade duration={0.5} delay={0.1} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 4"
          className="w-full h-full object-cover"
        />
      </div>
      </BlurFade>
      <BlurFade duration={0.5} delay={0.5} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 5"
          className="w-full h-full object-cover"
        />
      </div>
      </BlurFade>
     
      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

       <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

       <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

       <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade> 

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.1} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 4"
          className="w-full h-full object-cover"
        />
      </div>
      </BlurFade>
      <BlurFade duration={0.5} delay={0.5} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 5"
          className="w-full h-full object-cover"
        />
      </div>
      </BlurFade>
     
      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

       <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

       <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

       <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade> 

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>

      <BlurFade duration={0.5} delay={0.75} yOffset={10} inView>
      <div className="bg-gray-800 rounded-lg overflow-hidden shadow-lg aspect-[4/3] w-90 h-70">
        <img 
          src="/example.jpg" 
          alt="AI Generated Image 6"
          className="w-full h-full object-cover"
          />
        </div>
      </BlurFade>
      </div>
    </div>
  );
}